### ISSUE TITLE
not  working

### ISSUE THREAD

**Issue by noob-alert** [Sanketwable/Follow_Everyone_On_GITHUB#2]
I guess the api calls are getting `204` because I keep seeing the message 
```
404
need to sleep at this point
```

![Screenshot from 2021-02-26 11-08-23](https://user-images.githubusercontent.com/71872258/109260109-8bd34780-7823-11eb-95d7-5ce340520373.png)

**Comment by Sanketwable** [comment]
Hey @noob-alert When generating the token please select all the fields and generate the token. Reason is the API call will request for all the users on GITHUB and also need access to Follow.
<img width="1440" alt="Screenshot 2021-02-26 at 11 45 17 AM" src="https://user-images.githubusercontent.com/43716242/109262854-42d1c200-7828-11eb-9ede-121e02fb73e3.png">

**Comment by Sanketwable** [comment]
Try and reply if you are facing the same issue 

Thanks @noob-alert

**Comment by noob-alert** [comment]
why are there 204 errors? Also it is running but my profile is not reflecting the data
![Screenshot from 2021-02-26 12-22-10](https://user-images.githubusercontent.com/71872258/109266086-90046280-782d-11eb-980b-6a81098034a9.png)

**Comment by noob-alert** [comment]
BTW. thanks @Sanketwable

**Comment by Sanketwable** [comment]
204 is kind of status ok
Your profile will reflect data shortly.
